# Generated by Django 3.2.4 on 2023-09-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('nombreMarca', models.TextField(db_column='nombreMarca')),
            ],
            options={
                'db_table': 'Marcas',
            },
        ),
    ]
