# Generated by Django 3.2.4 on 2023-10-03 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('nombreCategoria', models.TextField(db_column='nombreCategoria', max_length=50)),
                ('descripcion', models.TextField(db_column='descripcion', max_length=150)),
            ],
            options={
                'db_table': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('idColor', models.AutoField(db_column='idColor', primary_key=True, serialize=False)),
                ('nombreColor', models.TextField(db_column='nombreColor', max_length=30)),
            ],
            options={
                'db_table': 'Colores',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('nombreGenero', models.TextField(db_column='nombreGenero', max_length=20)),
            ],
            options={
                'db_table': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('nombreMarca', models.TextField(db_column='nombreMarca', max_length=20)),
                ('descripcion', models.TextField(db_column='descripcion', max_length=150)),
            ],
            options={
                'db_table': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idMaterial', models.AutoField(db_column='idMaterial', primary_key=True, serialize=False)),
                ('nombreMaterial', models.TextField(db_column='nombreMaterial', max_length=30)),
            ],
            options={
                'db_table': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.AutoField(db_column='idPedido', primary_key=True, serialize=False)),
                ('fechaPedido', models.DateField(db_column='fechaPedido')),
                ('direccionEnvio', models.TextField(db_column='direccionEnvio', max_length=200)),
                ('estadoPedido', models.TextField(db_column='estadoPedido', max_length=20)),
                ('totalPedido', models.FloatField(db_column='totalPedido')),
                ('metodoPago', models.TextField(db_column='metodoPago', max_length=20)),
            ],
            options={
                'db_table': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombreProducto', models.TextField(db_column='nombreProducto', max_length=50)),
                ('descripcionProducto', models.TextField(db_column='descripcionProducto', max_length=100)),
                ('precioProducto', models.FloatField(db_column='precioProducto')),
                ('imagenProducto', models.ImageField(db_column='imagenProducto', upload_to='')),
                ('disponibilidadStock', models.IntegerField(db_column='disponibilidadStock')),
                ('fk_categoria', models.ForeignKey(db_column='fk_categoria', on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('fk_color', models.ForeignKey(db_column='fk_color', on_delete=django.db.models.deletion.CASCADE, to='api.color')),
                ('fk_genero', models.ForeignKey(db_column='fk_genero', on_delete=django.db.models.deletion.CASCADE, to='api.genero')),
                ('fk_marca', models.ForeignKey(db_column='fk_marca', on_delete=django.db.models.deletion.CASCADE, to='api.marca')),
                ('fk_material', models.ForeignKey(db_column='fk_material', on_delete=django.db.models.deletion.CASCADE, to='api.material')),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('idTalla', models.AutoField(db_column='idTalla', primary_key=True, serialize=False)),
                ('nombreTalla', models.FloatField(db_column='nombreTalla')),
            ],
            options={
                'db_table': 'Tallas',
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('idTemporada', models.AutoField(db_column='idTemporada', primary_key=True, serialize=False)),
                ('nombreTemporada', models.TextField(db_column='nombreTemporada', max_length=30)),
            ],
            options={
                'db_table': 'Temporadas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombreUsuario', models.TextField(db_column='nombreUsuario', max_length=50)),
                ('apellidoPaterno', models.TextField(db_column='apellidoPaterno', max_length=50)),
                ('apellidoMaterno', models.TextField(db_column='apellidoMaterno', max_length=50)),
                ('password', models.TextField(db_column='password', max_length=25)),
                ('correoElectronico', models.EmailField(db_column='correoElectronico', max_length=254, unique=True)),
                ('numeroTelefonico', models.IntegerField(db_column='numeroTelefonico')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Pedido',
            fields=[
                ('id_Usuario_has_Pedido', models.AutoField(db_column='id_Usuario_has_Pedido', primary_key=True, serialize=False)),
                ('fk_id_Pedido', models.ForeignKey(db_column='fk_id_Pedido', on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
                ('fk_id_Usuario', models.ForeignKey(db_column='fk_id_Usuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'Usuario_Pedido',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('idResena', models.AutoField(db_column='idResena', primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField(db_column='puntuacion')),
                ('comentario', models.TextField(db_column='comentario', max_length=200)),
                ('fk_producto', models.ForeignKey(db_column='fk_producto', on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'Resenas',
            },
        ),
        migrations.CreateModel(
            name='Producto_has_Talla',
            fields=[
                ('id_Producto_has_Talla', models.AutoField(db_column='id_Producto_has_Talla', primary_key=True, serialize=False)),
                ('fk_id_Producto', models.ForeignKey(db_column='fk_id_Producto', on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('fk_id_Talla', models.ForeignKey(db_column='fk_id_Talla', on_delete=django.db.models.deletion.CASCADE, to='api.talla')),
            ],
            options={
                'db_table': 'Producto_has_Talla',
            },
        ),
        migrations.CreateModel(
            name='Producto_has_Material',
            fields=[
                ('id_Producto_has_Material', models.AutoField(db_column='id_Producto_has_Material', primary_key=True, serialize=False)),
                ('fk_id_Material', models.ForeignKey(db_column='fk_id_Material', on_delete=django.db.models.deletion.CASCADE, to='api.material')),
                ('fk_id_Producto', models.ForeignKey(db_column='fk_id_Producto', on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
            options={
                'db_table': 'Producto_has_Material',
            },
        ),
        migrations.CreateModel(
            name='Producto_has_Color',
            fields=[
                ('id_Producto_has_Color', models.AutoField(db_column='id_Producto_has_Color', primary_key=True, serialize=False)),
                ('fk_id_Color', models.ForeignKey(db_column='fk_id_Color', on_delete=django.db.models.deletion.CASCADE, to='api.color')),
                ('fk_id_Producto', models.ForeignKey(db_column='fk_id_Producto', on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
            options={
                'db_table': 'Producto_has_Color',
            },
        ),
        migrations.CreateModel(
            name='Producto_has_Categoria',
            fields=[
                ('id_Producto_has_Categoria', models.AutoField(db_column='id_Producto_has_Categoria', primary_key=True, serialize=False)),
                ('fk_id_Categoria', models.ForeignKey(db_column='fk_id_Categoria', on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('fk_id_Producto', models.ForeignKey(db_column='fk_id_Producto', on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
            options={
                'db_table': 'Producto_has_Categoria',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='fk_talla',
            field=models.ForeignKey(db_column='fk_talla', on_delete=django.db.models.deletion.CASCADE, to='api.talla'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fk_temporada',
            field=models.ForeignKey(db_column='fk_temporada', on_delete=django.db.models.deletion.CASCADE, to='api.temporada'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fk_usuario',
            field=models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.CreateModel(
            name='CarroCompras',
            fields=[
                ('idCarroCompras', models.AutoField(db_column='idCarroCompras', primary_key=True, serialize=False)),
                ('numeroProducto', models.IntegerField(db_column='numeroProducto')),
                ('fk_producto', models.ForeignKey(db_column='fk_producto', on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'CarroCompras',
            },
        ),
    ]
