# Generated by Django 3.2.4 on 2023-09-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('nombreCategoria', models.TextField(db_column='nombreCategoria', max_length=50)),
                ('descripcion', models.TextField(db_column='descripcion', max_length=150)),
            ],
            options={
                'db_table': 'Categorias',
            },
        ),
    ]
