# Generated by Django 3.2.4 on 2023-09-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Talla',
        ),
    ]
