# Generated by Django 3.2.4 on 2023-09-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_delete_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('nombreMarca', models.TextField(db_column='nombreMarca', max_length=20)),
                ('descripcion', models.TextField(db_column='descripcion', max_length=150)),
            ],
            options={
                'db_table': 'Marcas',
            },
        ),
    ]
