# Generated by Django 3.2.4 on 2023-09-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_talla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('idColor', models.AutoField(db_column='idColor', primary_key=True, serialize=False)),
                ('nombreColor', models.TextField(db_column='nombreColor', max_length=30)),
            ],
            options={
                'db_table': 'Colores',
            },
        ),
    ]
