# Generated by Django 3.2.4 on 2023-09-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('idTalla', models.AutoField(db_column='idTalla', primary_key=True, serialize=False)),
                ('nombreColor', models.TextField(db_collation='nombreColor', max_length=20)),
            ],
            options={
                'db_table': 'Tallas',
            },
        ),
    ]
