# Generated by Django 3.2.4 on 2023-09-19 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
