# Generated by Django 3.2.4 on 2023-09-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talla',
            name='nombreColor',
            field=models.TextField(db_column='nombreColor', max_length=20),
        ),
    ]
