# Generated by Django 3.2.4 on 2023-09-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_talla_nombrecolor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Talla',
        ),
    ]
