# Generated by Django 3.2.4 on 2023-10-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usuario_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
    ]
