# Generated by Django 3.2.4 on 2023-09-19 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
