# Generated by Django 3.2.4 on 2023-10-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20231010_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombreUsuario',
            field=models.CharField(db_column='nombreUsuario', max_length=50),
        ),
    ]
