# Generated by Django 3.2.4 on 2023-09-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_talla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Talla',
        ),
    ]
