# Generated by Django 3.2.4 on 2023-10-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_usuario_nombreusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_Formulario', models.AutoField(db_column='id_Formulario', primary_key=True, serialize=False)),
                ('pregunta1', models.TextField(db_column='¿Qué busca en una tienda online?')),
                ('pregunta2', models.TextField(db_column='¿Qué forma de pago desea tener en una tienda online?')),
                ('pregunta3', models.TextField(db_column='¿En que dispositivos visita mas una tienda online?')),
                ('pregunta4', models.TextField(db_column='En una tienda online de calzado, ¿Qué tipo de calzado busca con mas frecuencia?')),
                ('pregunta5', models.TextField(db_column='¿Qué métodos de búsqueda prefiere para un tienda de calzado online? ')),
                ('pregunta6', models.TextField(db_column='¿Se basa de las opiniones y calificaciones de los demás para definir si comprar o no un producto online?')),
                ('pregunta7', models.TextField(db_column='¿Cómo prefieres la vista de productos online?')),
                ('pregunta8', models.TextField(db_column='¿Qué le gustaría tener por el uso y compra de productos online?')),
                ('pregunta9', models.TextField(db_column='¿Te gustaría recibir notificaciones o avisos sobre ofertas y promociones? ')),
                ('pregunta10', models.TextField(db_column='¿Qué método de registro prefieres en tiendas online?')),
            ],
            options={
                'db_table': 'Formulario',
            },
        ),
    ]
