# Generated by Django 3.2.4 on 2023-09-19 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_carrocompras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('idResena', models.AutoField(db_column='idResena', primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField(db_column='puntuacion')),
                ('comentario', models.TextField(db_column='comentario', max_length=200)),
                ('fk_producto', models.ForeignKey(db_column='fk_producto', on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'Resenas',
            },
        ),
    ]
