# Generated by Django 3.2.4 on 2023-09-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_talla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('idColor', models.AutoField(db_column='idColor', primary_key=True, serialize=False)),
                ('nombreColor', models.TextField(db_column='nombreColor', max_length=20)),
            ],
            options={
                'db_table': 'Colores',
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('idTalla', models.AutoField(db_column='idTalla', primary_key=True, serialize=False)),
                ('nombreTalla', models.IntegerField(db_column='nombreTalla')),
            ],
            options={
                'db_table': 'Tallas',
            },
        ),
    ]
