# Generated by Django 4.2.7 on 2023-12-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_producto_imagenproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fk_usuario',
        ),
        migrations.RemoveField(
            model_name='producto_has_categoria',
            name='fk_id_Categoria',
        ),
        migrations.RemoveField(
            model_name='producto_has_categoria',
            name='fk_id_Producto',
        ),
        migrations.RemoveField(
            model_name='producto_has_color',
            name='fk_id_Color',
        ),
        migrations.RemoveField(
            model_name='producto_has_color',
            name='fk_id_Producto',
        ),
        migrations.RemoveField(
            model_name='producto_has_material',
            name='fk_id_Material',
        ),
        migrations.RemoveField(
            model_name='producto_has_material',
            name='fk_id_Producto',
        ),
        migrations.RemoveField(
            model_name='producto_has_talla',
            name='fk_id_Producto',
        ),
        migrations.RemoveField(
            model_name='producto_has_talla',
            name='fk_id_Talla',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='fk_producto',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='fk_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario_has_pedido',
            name='fk_id_Pedido',
        ),
        migrations.RemoveField(
            model_name='usuario_has_pedido',
            name='fk_id_Usuario',
        ),
        migrations.RemoveField(
            model_name='carrocompras',
            name='numeroProducto',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='disponibilidadStock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fk_color',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fk_genero',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fk_material',
        ),
        migrations.AddField(
            model_name='producto',
            name='linkStripe',
            field=models.TextField(db_column='linkStripe', default='Pruebas', max_length=100),
        ),
        migrations.AlterField(
            model_name='marca',
            name='idMarca',
            field=models.AutoField(db_column='idMarca', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Producto_has_Categoria',
        ),
        migrations.DeleteModel(
            name='Producto_has_Color',
        ),
        migrations.DeleteModel(
            name='Producto_has_Material',
        ),
        migrations.DeleteModel(
            name='Producto_has_Talla',
        ),
        migrations.DeleteModel(
            name='Resena',
        ),
        migrations.DeleteModel(
            name='Usuario_has_Pedido',
        ),
    ]
