# Generated by Django 3.2.4 on 2023-10-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_resena'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='Producto',
        ),
        migrations.CreateModel(
            name='Usuario_Pedido',
            fields=[
                ('id_Usuario_has_Pedido', models.AutoField(db_column='id_Usuario_has_Pedido', primary_key=True, serialize=False)),
                ('fk_id_Pedido', models.ForeignKey(db_column='fk_id_Pedido', on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
                ('fk_id_Usuario', models.ForeignKey(db_column='fk_id_Usuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'Usuario_Pedido',
            },
        ),
        migrations.CreateModel(
            name='Producto_has_Talla',
            fields=[
                ('id_Producto_has_Talla', models.AutoField(db_column='id_Producto_has_Talla', primary_key=True, serialize=False)),
                ('fk_id_Producto', models.ForeignKey(db_column='fk_id_Producto', on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('fk_id_Talla', models.ForeignKey(db_column='fk_id_Talla', on_delete=django.db.models.deletion.CASCADE, to='api.talla')),
            ],
            options={
                'db_table': 'Producto_has_Talla',
            },
        ),
        migrations.CreateModel(
            name='Producto_has_Material',
            fields=[
                ('id_Producto_has_Material', models.AutoField(db_column='id_Producto_has_Material', primary_key=True, serialize=False)),
                ('fk_id_Material', models.ForeignKey(db_column='fk_id_Material', on_delete=django.db.models.deletion.CASCADE, to='api.material')),
                ('fk_id_Producto', models.ForeignKey(db_column='fk_id_Producto', on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
            options={
                'db_table': 'Producto_has_Material',
            },
        ),
        migrations.CreateModel(
            name='Producto_has_Color',
            fields=[
                ('id_Producto_has_Color', models.AutoField(db_column='id_Producto_has_Color', primary_key=True, serialize=False)),
                ('fk_id_Color', models.ForeignKey(db_column='fk_id_Color', on_delete=django.db.models.deletion.CASCADE, to='api.color')),
                ('fk_id_Producto', models.ForeignKey(db_column='fk_id_Producto', on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
            options={
                'db_table': 'Producto_has_Color',
            },
        ),
        migrations.CreateModel(
            name='Producto_has_Categoria',
            fields=[
                ('id_Producto_has_Categoria', models.AutoField(db_column='id_Producto_has_Categoria', primary_key=True, serialize=False)),
                ('fk_id_Categoria', models.ForeignKey(db_column='fk_id_Categoria', on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('fk_id_Producto', models.ForeignKey(db_column='fk_id_Producto', on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
            options={
                'db_table': 'Producto_has_Categoria',
            },
        ),
    ]
