# Generated by Django 4.2.7 on 2023-12-06 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_pedido_fk_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('idColor', models.AutoField(db_column='idColor', primary_key=True, serialize=False)),
                ('nombreColor', models.TextField(db_column='nombreColor', max_length=30)),
            ],
            options={
                'db_table': 'Temporadas',
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fk_temporada',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='Pruebas', upload_to='imagenes/'),
        ),
        migrations.DeleteModel(
            name='Temporada',
        ),
        migrations.AddField(
            model_name='producto',
            name='fk_color',
            field=models.ForeignKey(db_column='fk_color', default='Pruebas', on_delete=django.db.models.deletion.CASCADE, to='api.color'),
        ),
    ]
