# Generated by Django 4.2.7 on 2023-12-06 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_color_remove_producto_fk_temporada_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fk_color',
            field=models.ForeignKey(db_column='fk_color', on_delete=django.db.models.deletion.CASCADE, to='api.color'),
        ),
    ]
