# Generated by Django 4.2.7 on 2023-12-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_producto_fk_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='linkStripe',
            field=models.TextField(db_column='linkStripe', max_length=100),
        ),
    ]
