# Generated by Django 4.2.7 on 2023-12-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_producto_imagen_alter_producto_linkstripe'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='color',
            table='Color',
        ),
    ]
