# Generated by Django 4.2.7 on 2023-12-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_color_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carrocompras',
            table='CarroCompra',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='Categoria',
        ),
        migrations.AlterModelTable(
            name='talla',
            table='Talla',
        ),
    ]
